### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large for dtype('float64')

### ISSUE THREAD

**Issue by polchan** [eliza-m/NLRexpress#1]
Hi! Eliza.
I have more than 100 NLR sequences, so I downloaded this code.
But I met some errors during operations, this is my error code:

30/11/2022 12:17:55:    ############ NLRexpress started ############
30/11/2022 12:17:55:    Input FASTA: CNLA_part_1.fasta
30/11/2022 12:17:55:    Checking FASTA file - started
30/11/2022 12:17:55:    Checking FASTA file - done
30/11/2022 12:17:55:    Running JackHMMER - started
30/11/2022 13:51:46:    Running JackHMMER - done
30/11/2022 13:51:46:    Preparing features: Parsing HMM profile - started
30/11/2022 13:51:50:    Running CCexpress : started
30/11/2022 13:51:50:    Preparing features: NN input for motif extEDVID started
30/11/2022 13:51:52:    Preparing features: NN input for motif extEDVID done
Traceback (most recent call last):
  File "/ngsproject/bcguo/tools/NLRexpress/nlrexpress.py", line 200, in <module>
    predict()
  File "/ngsproject/bcguo/miniconda3/envs/nlrexpress/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/ngsproject/bcguo/miniconda3/envs/nlrexpress/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/ngsproject/bcguo/miniconda3/envs/nlrexpress/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/ngsproject/bcguo/miniconda3/envs/nlrexpress/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/ngsproject/bcguo/tools/NLRexpress/nlrexpress.py", line 111, in predict
    results[p] = CCexpress.predictors[p].model.predict_proba( X )
  File "/ngsproject/bcguo/miniconda3/envs/nlrexpress/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 1119, in predict_proba
    y_pred = self._forward_pass_fast(X)
  File "/ngsproject/bcguo/miniconda3/envs/nlrexpress/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 134, in _forward_pass_fast
    X = self._validate_data(X, accept_sparse=['csr', 'csc'], reset=False)
  File "/ngsproject/bcguo/miniconda3/envs/nlrexpress/lib/python3.9/site-packages/sklearn/base.py", line 421, in _validate_data
    X = check_array(X, **check_params)
  File "/ngsproject/bcguo/miniconda3/envs/nlrexpress/lib/python3.9/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/ngsproject/bcguo/miniconda3/envs/nlrexpress/lib/python3.9/site-packages/sklearn/utils/validation.py", line 720, in check_array
    _assert_all_finite(array,
  File "/ngsproject/bcguo/miniconda3/envs/nlrexpress/lib/python3.9/site-packages/sklearn/utils/validation.py", line 103, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

Can you help solve this problem?
Thanks

**Comment by eliza-m** [comment]
Hi,

Thank you for noticing this ! 
Could you please send me an input example that generated the error, to try to reproduce it ? (my address: elizamartinc{at}yahoo.com)
Also, does the input example from '/sample/input/zar1_rpp1.fa' yields the same error ?
Thank you !

Best,
Eliza

**Comment by polchan** [comment]
Ok, I have sent mail to you.
